trigger:
  branches:
    include:
      - master
  paths:
    include:
      - chocolatey/upack/*
      - package.yml

extends:
  template: ../package.yml
  parameters:
    packageName: upack
    packageLongName: UPack