trigger:
  branches:
    include:
      - master
  paths:
    include:
      - chocolatey/azure-agent/*
      - package.yml

extends:
  template: ../package.yml
  parameters:
    packageName: azure-agent
    packageLongName: Azure DevOps Agent