trigger:
  branches:
    include:
      - master
  paths:
    include:
      - chocolatey/dotnet-472/*
      - package.yml

extends:
  template: ../package.yml
  parameters:
    packageName: dotnet-472
    packageLongName: Microsoft .NET Framework 4.7.2