- name: Read gossip encryption key
  hashivault_read:
    secret: "{{ vault.secrets.gossip }}"
    key: key
    version: 2
  register: gossip_read
  run_once: true
  delegate_to: localhost
- set_fact:
    enc_key: "{{ gossip_read.value }}"
- name: Create server configuration
  ansible.builtin.template:
    src: files/server_config.j2
    dest: "{{ path.config }}"
    owner: "{{ service.user }}"
    group: "{{ service.group }}"
  when: server
- name: Create client configuration
  ansible.builtin.template:
    src: files/client_config.j2
    dest: "{{ path.config }}"
    owner: "{{ service.user }}"
    group: "{{ service.group }}"
  when: not server