- name: Generate service file
  ansible.builtin.template:
    src: files/service.j2
    dest: /lib/systemd/system/consul.service
- name: Enable Consul service
  ansible.builtin.service:
    name: consul
    enabled: yes
  register: service