- name: Generate service file
  ansible.builtin.template:
    src: files/service.j2
    dest: /lib/systemd/system/consul.service
- name: Enable and start Consul service
  ansible.builtin.service:
    name: consul
    enabled: yes
    state: started
  register: service
- name: Wait for Consul cluster to bootstrap
  pause:
    seconds: 60
  when: service.changed