trigger:
  branches:
    include:
      - master
  paths:
    include:
      - chocolatey/sql-2014-clr/*
      - package.yml

extends:
  template: ../package.yml
  parameters:
    packageName: sql-2014-clr
    packageLongName: Microsoft System CLR Types for SQL Server 2014