trigger:
  branches:
    include:
      - master
  paths:
    include:
      - chocolatey/python/*
      - package.yml

extends:
  template: ../package.yml
  parameters:
    packageName: python
    packageLongName: Python 3