trigger:
  branches:
    include:
      - master
  paths:
    include:
      - chocolatey/sql-express-adv/*
      - package.yml

extends:
  template: ../package.yml
  parameters:
    packageName: sql-express-adv
    packageLongName: Microsoft SQL Express (Advanced)