package updater

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestNew(t *testing.T) {
	t.Run("valid replacements", func(t *testing.T) {
		replacements := []Replacement{
			{Pattern: `url\s*=\s*"[^"]*"`, Value: `url = "{{ .Source.URL }}"`},
		}
		data := TemplateData{Source: SourceData{URL: "https://example.com"}}

		updater, err := New(replacements, data)

		require.NoError(t, err)
		assert.NotNil(t, updater)
		assert.Len(t, updater.replacements, 1)
	})

	t.Run("invalid regex pattern", func(t *testing.T) {
		replacements := []Replacement{
			{Pattern: `[invalid`, Value: "test"},
		}
		data := TemplateData{}

		updater, err := New(replacements, data)

		assert.Nil(t, updater)
		assert.Error(t, err)
		assert.Contains(t, err.Error(), "compile pattern")
	})

	t.Run("invalid template", func(t *testing.T) {
		replacements := []Replacement{
			{Pattern: `test`, Value: `{{ .Invalid`},
		}
		data := TemplateData{}

		updater, err := New(replacements, data)

		assert.Nil(t, updater)
		assert.Error(t, err)
		assert.Contains(t, err.Error(), "parse template")
	})
}

func TestFileUpdater_UpdateContent(t *testing.T) {
	tests := []struct {
		name         string
		replacements []Replacement
		data         TemplateData
		content      string
		want         string
		wantModified bool
	}{
		{
			name: "simple URL replacement",
			replacements: []Replacement{
				{Pattern: `url\s*=\s*"[^"]*"`, Value: `url = "{{ .Source.URL }}"`},
			},
			data:         TemplateData{Source: SourceData{URL: "https://new.example.com/file.iso"}},
			content:      `url = "https://old.example.com/old.iso"`,
			want:         `url = "https://new.example.com/file.iso"`,
			wantModified: true,
		},
		{
			name: "checksum replacement",
			replacements: []Replacement{
				{Pattern: `checksum\s*=\s*"[^"]*"`, Value: `checksum = "{{ .Source.Checksum }}"`},
			},
			data:         TemplateData{Source: SourceData{Checksum: "sha256:abc123"}},
			content:      `checksum = "sha256:old"`,
			want:         `checksum = "sha256:abc123"`,
			wantModified: true,
		},
		{
			name: "multiple replacements",
			replacements: []Replacement{
				{Pattern: `vyos_iso_url\s*=\s*"[^"]*"`, Value: `vyos_iso_url = "{{ .Source.URL }}"`},
				{Pattern: `vyos_iso_checksum\s*=\s*"[^"]*"`, Value: `vyos_iso_checksum = "{{ .Source.Checksum }}"`},
			},
			data: TemplateData{Source: SourceData{
				URL:      "https://new.example.com/vyos.iso",
				Checksum: "sha256:newchecksum",
			}},
			content: `vyos_iso_url = "https://old.example.com/vyos.iso"
vyos_iso_checksum = "sha256:oldchecksum"`,
			want: `vyos_iso_url = "https://new.example.com/vyos.iso"
vyos_iso_checksum = "sha256:newchecksum"`,
			wantModified: true,
		},
		{
			name: "no match - no modification",
			replacements: []Replacement{
				{Pattern: `nonexistent_pattern`, Value: `replacement`},
			},
			data:         TemplateData{},
			content:      `some content that does not match`,
			want:         `some content that does not match`,
			wantModified: false,
		},
		{
			name: "pattern matches but value same - no modification",
			replacements: []Replacement{
				{Pattern: `url = "same"`, Value: `url = "same"`},
			},
			data:         TemplateData{},
			content:      `url = "same"`,
			want:         `url = "same"`,
			wantModified: false,
		},
		{
			name: "HCL packer vars format",
			replacements: []Replacement{
				{Pattern: `vyos_iso_url\s*=\s*"[^"]*"`, Value: `vyos_iso_url = "{{ .Source.URL }}"`},
			},
			data: TemplateData{Source: SourceData{URL: "https://github.com/vyos/releases/vyos-1.5.iso"}},
			content: `# Auto-generated by labctl images sync
vyos_iso_url      = "https://old-url.example.com/vyos.iso"
vyos_iso_checksum = "sha256:abc123"
`,
			want: `# Auto-generated by labctl images sync
vyos_iso_url = "https://github.com/vyos/releases/vyos-1.5.iso"
vyos_iso_checksum = "sha256:abc123"
`,
			wantModified: true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			updater, err := New(tt.replacements, tt.data)
			require.NoError(t, err)

			got, modified, err := updater.UpdateContent([]byte(tt.content))

			require.NoError(t, err)
			assert.Equal(t, tt.want, string(got))
			assert.Equal(t, tt.wantModified, modified)
		})
	}
}

func TestFileUpdater_UpdateFile(t *testing.T) {
	t.Run("updates file and preserves permissions", func(t *testing.T) {
		dir := t.TempDir()
		path := filepath.Join(dir, "test.hcl")

		content := `vyos_iso_url = "https://old.example.com/old.iso"`
		err := os.WriteFile(path, []byte(content), 0o644) //nolint:gosec // G306: test file
		require.NoError(t, err)

		replacements := []Replacement{
			{Pattern: `vyos_iso_url\s*=\s*"[^"]*"`, Value: `vyos_iso_url = "{{ .Source.URL }}"`},
		}
		data := TemplateData{Source: SourceData{URL: "https://new.example.com/new.iso"}}
		updater, err := New(replacements, data)
		require.NoError(t, err)

		modified, err := updater.UpdateFile(path)

		require.NoError(t, err)
		assert.True(t, modified)

		// Verify content was updated
		got, err := os.ReadFile(path) //nolint:gosec // G304: test file from t.TempDir()
		require.NoError(t, err)
		assert.Equal(t, `vyos_iso_url = "https://new.example.com/new.iso"`, string(got))

		// Verify permissions preserved
		info, err := os.Stat(path)
		require.NoError(t, err)
		assert.Equal(t, os.FileMode(0o644), info.Mode().Perm())
	})

	t.Run("returns false when no changes", func(t *testing.T) {
		dir := t.TempDir()
		path := filepath.Join(dir, "test.hcl")

		content := `some other content`
		err := os.WriteFile(path, []byte(content), 0o644) //nolint:gosec // G306: test file
		require.NoError(t, err)

		replacements := []Replacement{
			{Pattern: `nonexistent`, Value: `replacement`},
		}
		updater, err := New(replacements, TemplateData{})
		require.NoError(t, err)

		modified, err := updater.UpdateFile(path)

		require.NoError(t, err)
		assert.False(t, modified)
	})

	t.Run("returns error for nonexistent file", func(t *testing.T) {
		updater, err := New([]Replacement{}, TemplateData{})
		require.NoError(t, err)

		modified, err := updater.UpdateFile("/nonexistent/path/file.txt")

		assert.False(t, modified)
		assert.Error(t, err)
		assert.Contains(t, err.Error(), "read file")
	})
}
