trigger:
  branches:
    include:
      - master
  paths:
    include:
      - chocolatey/chrome-enterprise/*
      - package.yml

extends:
  template: ../package.yml
  parameters:
    packageName: chrome-enterprise
    packageLongName: Google Chrome Enterprise