trigger:
  branches:
    include:
      - master
  paths:
    include:
      - chocolatey/proget/*
      - package.yml

extends:
  template: ../package.yml
  parameters:
    packageName: proget
    packageLongName: ProGet