trigger:
  branches:
    include:
      - master
  paths:
    include:
      - centos/iso.pkr.hcl
      - centos/cntos8/*
      - centos/scripts/bootstrap.sh

variables:
  os: centos
  image: cntos8
  type: iso

jobs:
- job: Default
  timeoutInMinutes: 120
  pool:
    name: Lab
    demands:
      - agent.os -equals Linux
  steps:
  - task: AzureAppConfiguration@3
    inputs:
      azureSubscription: 'Lab Resource Group'
      ConfigstoreName: 'GLabConfig'
      KeyFilter: '*'
      Label: 'vcenter'
  - task: AzureAppConfiguration@3
    inputs:
      azureSubscription: 'Lab Resource Group'
      ConfigstoreName: 'GLabConfig'
      KeyFilter: '*'
      Label: 'packer'
  - task: PowerShell@2
    displayName: 'Build CentOS 8 packer image'
    inputs:
      filePath: build.ps1
      arguments: -Os $(os) -Image $(image) -Type $(type)
      workingDirectory: $(Build.SourcesDirectory)/centos
      pwsh: true
    env:
      VCENTER_USER: $(vcenter.username)
      VCENTER_PASS: $(vcenter.password)
      ADMIN_PASS: $(packer.admin.password)