---
- name: Ubuntu 20.04 base playbook
  hosts: all
  become: yes
  tasks:
    - name: Enable passwordless sudo
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%sudo'
        line: '%sudo ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'
    - name: Change admin password
      user:
        name: admin
        update_password: always
        password: "{{ lookup('env', 'ADMIN_PASSWORD')|password_hash('sha512') }}"
    - name: Upgrade system
      ansible.builtin.apt:
        update_cache: yes
        upgrade: yes
    - name: Install base packages
      ansible.builtin.apt:
        name:
          - unzip
          - wget
    - name: Install cloud init support
      ansible.builtin.shell: "curl -sSL https://raw.githubusercontent.com/vmware/cloud-init-vmware-guestinfo/master/install.sh | sh -"
    - name: Add Hashicorp apt signing key
      ansible.builtin.apt_key:
        url: https://apt.releases.hashicorp.com/gpg
        state: present
    - name: Add Hashicorp repository
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://apt.releases.hashicorp.com focal main
        state: present
    - name: Install Hashicorp packages
      ansible.builtin.apt:
        update_cache: yes
        name:
          - consul
          - vault
    - name: Configure SSH daemon
      ansible.builtin.copy:
        src: files/sshd_config
        dest: /etc/ssh/sshd_config
    - name: Write SSH CA public key
      ansible.builtin.copy:
        content: "{{ lookup('env', 'SSH_CA') }}"
        dest: /etc/ssh/trusted
    - name: Remove default netplan and cloud-init configs
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /etc/netplan/00-installer-config.yaml
        - /etc/cloud/cloud.cfg.d/90_dpkg.cfg
        - /etc/cloud/cloud.cfg.d/99-installer.cfg
        - /etc/cloud/cloud.cfg.d/curtin-preserve-sources.cfg
        - /etc/cloud/cloud.cfg.d/subiquity-disable-cloudinit-networking.cfg