run:
  timeout: 5m

version: "2"

linters:
  disable-all: true
  enable:
    - govet
    - staticcheck
    - revive
    - errcheck
    - ineffassign
    - unused
    - gosec
    - gocritic
    - misspell
    - sqlclosecheck
    - bidichk

  settings:
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
      disabled-checks:
        - whyNoLint
        - wrapperFunc
        - hugeParam
        - rangeValCopy

    revive:
      rules:
        - name: exported
        - name: unused-parameter
        - name: unreachable-code
        - name: redefines-builtin-id
        - name: defer
        - name: context-as-argument
        - name: context-keys-type
        - name: error-return
        - name: error-naming
        - name: if-return
        - name: increment-decrement
        - name: var-naming
        - name: var-declaration
        - name: package-comments
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: unexported-return
        - name: indent-error-flow
        - name: errorf
        - name: empty-block
        - name: superfluous-else
        - name: unused-receiver
        - name: get-return
        - name: string-of-int
        - name: early-return
        - name: unconditional-recursion
        - name: identical-branches
        - name: waitgroup-by-value
        - name: atomic

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
