trigger:
  branches:
    include:
      - master
  paths:
    include:
      - windows/iso.pkr.hcl
      - windows/ws2016gui/*
      - windows/scripts/bootstrap.ps1
      - windows/scripts/change-pass.ps1
      - windows/scripts/enable-rdp.ps1
      - windows/scripts/enable-winrm.ps1
      - windows/scripts/install-vm-tools.ps1
      - windows/scripts/undo-winrmconfig.ps1

variables:
  os: windows
  image: ws2016gui
  type: iso
  packer.vars: "@{}"

jobs:
- job: Default
  timeoutInMinutes: 120
  pool:
    name: Lab
    demands:
      - agent.os -equals Linux
  steps:
  - task: AzureAppConfiguration@3
    inputs:
      azureSubscription: 'Lab Resource Group'
      ConfigstoreName: 'GLabConfig'
      KeyFilter: '*'
      Label: 'vcenter'
  - task: AzureAppConfiguration@3
    inputs:
      azureSubscription: 'Lab Resource Group'
      ConfigstoreName: 'GLabConfig'
      KeyFilter: '*'
      Label: 'packer'
  - task: AzureAppConfiguration@3
    inputs:
      azureSubscription: 'Lab Resource Group'
      ConfigstoreName: 'GLabConfig'
      KeyFilter: '*'
      Label: 'proget'
  - task: PowerShell@2
    displayName: 'Build Windows Server 2016 GUI packer image'
    inputs:
      filePath: build.ps1
      arguments: -Os $(os) -Image $(image) -Type $(type) -Variables $(packer.vars)
      workingDirectory: $(Build.SourcesDirectory)/windows
      pwsh: true
    env:
      VCENTER_USER: $(vcenter.username)
      VCENTER_PASS: $(vcenter.password)
      ADMIN_PASS: $(packer.admin.password)