trigger:
  branches:
    include:
      - master
  paths:
    include:
      - chocolatey/packer/*
      - package.yml

extends:
  template: ../package.yml
  parameters:
    packageName: packer
    packageLongName: Packer