---
- name: Enable KV secrets engine
  hashivault_secret_engine:
    name: secret
    backend: kv-v2
- name: Import secrets
  hashivault_secret:
    secret: "{{ item.path }}"
    data: "{{ item.data }}"
  with_items: "{{ vault.engines.kv.secrets }}"