---
- name: Create policies
  hashivault_policy:
    name: "{{ item.key }}"
    rules: "{{ lookup('template', 'templates/policy.j2') }}"
  vars:
    policies: "{{ item.value }}"
  with_dict: "{{ vault.policies }}"