---
- name: Enable transit backend
  hashivault_secret_engine:
    name: "{{ vault.engines.transit.mount }}"
    backend: transit
- name: Create transit keys
  include_tasks: transit_key.yml
  with_dict: "{{ vault.engines.transit['keys'] }}"