- name: Check if policy exists
  ansible.builtin.uri:
    url: "https://127.0.0.1:4646/v1/acl/policy/{{ item.name }}"
    validate_certs: no # https://github.com/ansible/ansible/issues/75015
    headers:
      X-Nomad-Token: "{{ token.value }}"
  ignore_errors: true
  register: policy_check
  run_once: true
- name: Create policy
  ansible.builtin.uri:
    url: "https://127.0.0.1:4646/v1/acl/policy/{{ item.name }}"
    method: POST
    body:
      name: "{{ item.name }}"
      description: "{{ item.desc }}"
      rules: "{{ lookup('template', 'files/policy.j2') }}"
    body_format: json
    validate_certs: no
    headers:
      X-Nomad-Token: "{{ token.value }}"
  run_once: true
  when: policy_check.status == 404
- name: Update policy
  ansible.builtin.uri:
    url: "https://127.0.0.1:4646/v1/acl/policy/{{ item.name }}"
    method: POST
    body:
      name: "{{ item.name }}"
      description: "{{ item.desc }}"
      rules: "{{ lookup('template', 'files/policy.j2') }}"
    body_format: json
    validate_certs: no
    headers:
      X-Nomad-Token: "{{ token.value }}"
  run_once: true
  when: policy_check.status != 404 and policy_check.json.Rules != lookup('template', 'files/policy.j2')