trigger:
  branches:
    include:
      - master
  paths:
    include:
      - chocolatey/iis-url-rewrite/*
      - package.yml

extends:
  template: ../package.yml
  parameters:
    packageName: iis-url-rewrite
    packageLongName: URL Rewrite