trigger:
  branches:
    include:
      - master
  paths:
    include:
      - chocolatey/eps.extension/*
      - package.yml

extends:
  template: ../package.yml
  parameters:
    packageName: eps.extension
    packageLongName: EPS Chocolatey Extension