trigger:
  branches:
    include:
      - master
  paths:
    include:
      - chocolatey/vcredist/*
      - package.yml

extends:
  template: ../package.yml
  parameters:
    packageName: vcredist
    packageLongName: Microsoft Visual C++ Redistributable